### ISSUE TITLE
secure secrets

### ISSUE THREAD

**Issue by matthiasbalke** [uglyoldbob/decompiler#1]
in your travis log file the secrets e.g. `sonar.login` are shown. you have to keep them secret otherwise everybody has access to your accounts!

I randomly found your output as I was browsing this post: http://stackoverflow.com/questions/38375162/not-authorized-to-execute-any-sonarqube-analysis-with-sonarqube-scanner-on-travi

**Comment by uglyoldbob** [comment]
I need to do something about this, but do not know how to resolve it.

**Comment by matthiasbalke** [comment]
You should check out the official docs, about encrypting keys: https://docs.travis-ci.com/user/encryption-keys/

**Comment by uglyoldbob** [comment]
Ok i think i have updated it according to the docs. It's not working. I'm fairly certain I have done something dumb or missed something simple. sonar-scanner fails with "Please check the properties sonar.login and sonar.password".

**Comment by uglyoldbob** [comment]
I believe I have this resolved with the latest revisions. Please re-open if it is noted to be untrue.
