### ISSUE TITLE
Include information that udis is required

### ISSUE THREAD

**Issue by rfalke** [uglyoldbob/decompiler#5]
Because of different aclocal version I had to execute "autoreconf -vfi". This failed because udis is required. A " tar xfvz ../Download/udis86-1.7.2.tar.gz" solved this. But it should be included in the README.

**Comment by uglyoldbob** [comment]
Good point. I think the configure.ac should also have some lines to detect if this condition is satisfied.

**Comment by uglyoldbob** [comment]
I have added udis86 as a git submodule. Need to put together some quick instructions for initial setup.

**Comment by RandomInsano** [comment]
It doesn't seem to have helped? I'm on macOS over here and tried installing udis86 from Homebrew. That seems to work as I can use `udcli` just fine but it's throwing this during the configure step:

```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating ac_config.h
config.status: executing depfiles commands
=== configuring in udis86 (/Users/edwinamsler/Documents/Code/rust/other/decompiler/build/udis86)
configure: WARNING: no configuration information is in udis86
```

**Comment by uglyoldbob** [comment]
I believe this is because the build system assumes that udis86 will be built from source, rather than it being provided as an external precompiled library.

**Comment by uglyoldbob** [comment]
The udis86 library is a git submodule now. The readme defines how to checkout the repo and get the submodule as well.
